### ISSUE TITLE
There are no uncles under Blocks

### ISSUE THREAD

**Issue by ales-tsurko** [Moneyfactory-io/blockscout-frontend#39]
Reported by testers.

<img width="484" alt="Screenshot 2024-04-29 at 18 54 31" src="https://github.com/Atleta-network/blockscout/assets/8686568/75fa8072-2f7f-4028-acff-461f37889b8b">

**Comment by r8bywork** [comment]
Related methods are functioning properly, but it's possible that there are simply no uncle blocks present in the blockchain at the moment.
