### ISSUE TITLE
Configure nginx reloading when ssl certificates are updated

### ISSUE THREAD

**Issue by ales-tsurko** [Moneyfactory-io/blockscout-frontend#55]
nginx should automatically reload when certbot updates certificates. This affects two **polkadot explorer** and **blockscout**.

**Comment by semeniak97mf** [comment]
https://github.com/Atleta-network/blockscout/pull/56

**Comment by semeniak97mf** [comment]
For polkadot-js: https://github.com/Atleta-network/polkadot-js-apps/pull/16
